require at least text 1.1.1.3, the first version to expose the "Array" constructor
Otherwise, the following occurs:

src/Data/Hashabler.hs:1088:24:
    Not in scope: data constructor ‘T.Array’
    Perhaps you meant ‘P.Array’ (imported from Data.Primitive)